Repository atls/hyperion, pull requests merged in 2023-10, with the labels that each got.

#507 fix/theme-readme
  ui-proto/theme/README.md
Labels: bug

#510 chore: update dependencies hidden-input, events-state
  .pnp.cjs
  .yarn/cache/@types-jest-npm-29.5.6-fa191e2675-49f2ea0763.zip
  ui-admin/button/src/button.component.tsx
  ui-admin/design/server.js
  ui-admin/icons/src/bag.icon.tsx
  ui-admin/icons/src/chart.icon.tsx
  ui-admin/icons/src/check.icon.tsx
  ui-admin/icons/src/close.icon.tsx
  ui-admin/icons/src/drag.icon.tsx
  ui-admin/icons/src/index.ts
  ui-admin/icons/src/loading.icon.tsx
  ui-admin/icons/src/logo.icon.tsx
  ui-admin/icons/src/pencil.icon.tsx
  ui-admin/icons/src/ruby.icon.tsx
  ui-admin/icons/src/trash.icon.tsx
  ui-admin/icons/src/upload.icon.tsx
  ui-admin/icons/src/user.icon.tsx
  ui-admin/icons/src/users.icon.tsx
  ui-parts/events-state/package.json
  ui-parts/events-state/src/events-state.utils.ts
  ui-parts/hidden-input/package.json
  ui-parts/hidden-input/src/hidden-input.component.ts
  ui-proto/autocomplete/src/autocomplete.stories.tsx
  ui-proto/avatar/src/avatar.component.tsx
  ui-proto/theme/README.md
  ui-proto/theme/src/index.ts
  ui/design/server.js
  yarn.lock
Labels: chore

#513 chore(checkbox): update code to publish package
  ui-parts/checkbox/src/container/base/base.styles.ts
Labels: feature

#512 fix(datepicker): update dependencies
  .pnp.cjs
  .yarn/cache/@types-react-datepicker-npm-4.15.0-6db90fe0cc-7febb5ce92.zip
  .yarn/cache/@types-react-datepicker-npm-4.19.1-cb4dee6466-95cdbde98b.zip
  .yarn/cache/react-datepicker-npm-4.16.0-c94778dc5d-8354e0884b.zip
  .yarn/cache/react-datepicker-npm-4.21.0-91a0215eb6-8976cbaea1.zip
  ui-admin/icons/src/bag.icon.tsx
  ui-admin/icons/src/chart.icon.tsx
  ui-admin/icons/src/check.icon.tsx
  ui-admin/icons/src/close.icon.tsx
  ui-admin/icons/src/drag.icon.tsx
  ui-admin/icons/src/index.ts
  ui-admin/icons/src/loading.icon.tsx
  ui-admin/icons/src/logo.icon.tsx
  ui-admin/icons/src/pencil.icon.tsx
  ui-admin/icons/src/ruby.icon.tsx
  ui-admin/icons/src/trash.icon.tsx
  ui-admin/icons/src/upload.icon.tsx
  ui-admin/icons/src/user.icon.tsx
  ui-admin/icons/src/users.icon.tsx
  ui-parts/datepicker/package.json
  ui-parts/datepicker/src/datepicker.interface.ts
  yarn.lock
Labels: bug

#515 feat(datepicker): WIP update base styles
  ui-parts/datepicker/src/datepicker.component.tsx
  ui-parts/datepicker/src/styles/appearance/appearance.interfaces.ts
  ui-parts/datepicker/src/styles/base/base.styles.ts
Labels: feature
