Repository atls/hyperion, pull requests merged in 2024-08, with the labels that each got.

#554 Feat: github actions renew
  .github/workflows/checks.yaml
  .github/workflows/publish.yaml
  .github/workflows/release.yaml
  .github/workflows/version.yaml
Labels: feature

#557 feat(github): adjust checks and release
  .github/workflows/checks.yaml
  .github/workflows/release.yaml
Labels: feature

#563 chore(common): publish theme packages
  .yarn/versions/3095e196.yml
  ui-admin/theme/package.json
  ui-parts/theme/package.json
Labels: chore

#564 chore(common): apply versions
  .yarn/versions/3095e196.yml
  .yarn/versions/b2ee12fa.yml
  ui-admin/theme/package.json
  ui-parts/theme/package.json
Labels: chore

#569 fix(design): dependencies
  ui-admin/design/package.json
  ui-admin/design/server.js
  ui/design/package.json
  ui/design/server.js
Labels: bug
