Repository atls/hyperion, pull requests merged in 2024-01, with the labels that each got.

#531 Feat/add controlled props for height width
  .pnp.cjs
  ui-admin/icons/src/bag.icon.tsx
  ui-admin/icons/src/chart.icon.tsx
  ui-admin/icons/src/check.icon.tsx
  ui-admin/icons/src/close.icon.tsx
  ui-admin/icons/src/drag.icon.tsx
  ui-admin/icons/src/index.ts
  ui-admin/icons/src/loading.icon.tsx
  ui-admin/icons/src/logo.icon.tsx
  ui-admin/icons/src/pencil.icon.tsx
  ui-admin/icons/src/ruby.icon.tsx
  ui-admin/icons/src/trash.icon.tsx
  ui-admin/icons/src/upload.icon.tsx
  ui-admin/icons/src/user.icon.tsx
  ui-admin/icons/src/users.icon.tsx
  ui-parts/button/README.md
  ui-parts/layout/package.json
  ui-parts/layout/src/box/__snapshots__/box.test.tsx.snap
  ui-parts/layout/src/box/box.component.ts
  ui-parts/layout/src/box/box.interfaces.ts
  ui-parts/layout/src/box/box.test.tsx
  ui-parts/layout/src/column/__snapshots__/column.test.tsx.snap
  ui-parts/layout/src/column/column.test.tsx
  ui-parts/layout/src/layout/__snapshots__/layout.test.tsx.snap
  ui-parts/layout/src/layout/layout.component.ts
  ui-parts/layout/src/layout/layout.interfaces.tsx
  ui-parts/layout/src/layout/layout.test.tsx
  ui-parts/layout/src/row/__snapshots__/row.test.tsx.snap
  ui-parts/layout/src/row/row.test.tsx
  ui-parts/layout/src/styles/full-viewport-height.styles.ts
  ui-parts/layout/src/styles/full-viewport-width.styles.ts
  ui-parts/layout/src/styles/index.ts
  ui-parts/layout/src/styles/styles.interfaces.ts
  ui-parts/text-transform/src/text-transform.interfaces.ts
  ui-proto/layout/package.json
  ui-proto/layout/src/index.ts
  ui-proto/text/package.json
  yarn.lock
Labels: feature

#532 feat: add NextImage component
  .pnp.cjs
  .yarnrc.yml
  ui-admin/icons/src/bag.icon.tsx
  ui-admin/icons/src/chart.icon.tsx
  ui-admin/icons/src/check.icon.tsx
  ui-admin/icons/src/close.icon.tsx
  ui-admin/icons/src/drag.icon.tsx
  ui-admin/icons/src/index.ts
  ui-admin/icons/src/loading.icon.tsx
  ui-admin/icons/src/logo.icon.tsx
  ui-admin/icons/src/pencil.icon.tsx
  ui-admin/icons/src/ruby.icon.tsx
  ui-admin/icons/src/trash.icon.tsx
  ui-admin/icons/src/upload.icon.tsx
  ui-admin/icons/src/user.icon.tsx
  ui-admin/icons/src/users.icon.tsx
  ui-parts/next-image/package.json
  ui-parts/next-image/src/index.ts
  ui-parts/next-image/src/next-image.component.tsx
  ui-parts/next-image/src/next-image.styles.ts
  yarn.lock
Labels: feature

#533 feat/license
  LICENSE
Labels: feature

#540 chore/trigger-theme
  ui-proto/theme/src/interface.d.ts
Labels: chore

#543 fix: ui-parts/text dependencies
  .pnp.cjs
  ui-parts/text/package.json
  ui-parts/text/src/text.component.tsx
  yarn.lock
Labels: bug
